model_id = "mlx-community/GLM-5.3-MLX-8bit"
n_layers = 78
hidden_size = 6144
num_key_value_heads = 64
supports_tensor = true
tasks = ["TextGeneration"]
backends = ["MlxMetal", "MlxCpu", "MlxCuda", "Vllm"]
context_length = 1048576
trust_remote_code = false
default_reasoning_effort = "low"

[storage_size]
in_bytes = 790134748121
