from collections.abc import Iterator
from mlx import core as mx

class KVCache:
    def size(self) -> int: ...

class ArraysCache:
    state: list[mx.array | None]
    def __init__(self, size: int): ...
    def size(self) -> int: ...
    def trim(self, count: int) -> int: ...
    def is_trimmable(self) -> bool: ...

class CacheList:
    caches: tuple[object, ...]
    state: list[object]
    def __iter__(self) -> Iterator[object]: ...
    def size(self) -> int: ...
    def trim(self, count: int) -> int: ...
    def is_trimmable(self) -> bool: ...
